name: gou
description: A simple command-line application.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.12.0 <3.0.0'

# dependencies:
#   path: ^1.8.0
dependencies:
  dio: 4.0.0
  logger: ^1.1.0
  crypto: 3.0.1
dev_dependencies:
  pedantic: ^1.10.0
